<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Courses Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h2 { margin: 0; }
        .info { text-align: right; font-size: 10px; color: #555; margin-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table, th, td { border: 1px solid #ddd; }
        th, td { padding: 8px; text-align: center; }
        th { background-color: #f2f2f2; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        @page {
            margin: 100px 25px;
        }

        footer {
            position: fixed;
            bottom: -30px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 10px;
            color: #555;
        }

        .page-number:after {
            content: counter(page) " of " counter(pages);
        }

    </style>
</head>
<body>
    <div class="header">
        <h2>Courses Report</h2>
    </div>
    <div class="info">
        <img src="{{ public_path('assets/images/logo/TaalemHub-Logo-Design.png') }}" 
             alt="logo" 
             style="height: 40px; margin-bottom: 5px;"/>
        <br>
        Generated on: {{ now()->format('d/m/Y H:i') }}
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Course</th>
                <th>Category</th>
                <th>Instructor</th>
                <th>Start - End</th>
                <th>Price</th>
                <th>Students</th>
                <th>Assignments</th>
            </tr>
        </thead>
        <tbody>
            @foreach($courses as $index => $course)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $course->title }}</td>
                <td>{{ $course->category->name ?? '-' }}</td>
                <td>{{ $course->instructor->full_name ?? '-' }}</td>
                <td>{{ $course->start_date?->format('d/m/Y') ?? '-' }} - {{ $course->end_date?->format('d/m/Y') ?? '-' }}</td>
                <td>${{ number_format($course->price, 2) }}</td>
                <td>{{ $course->students_count ?? 0 }}</td>
                <td>{{ $course->assignments->count() ?? 0 }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <footer>
        Generated by TaleemHub | Page: <span class="page-number"></span>
    </footer>
</body>
</html>
